---
title: "Rashomon -- Four Conflicting Views of Diversity in Tech -- Version 0.41"
author: "Roy L Beasley, PhD — DLL Editor"
date: "1/19/2017"
output: 
 prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
    toc_depth: 4
    fig_width: 7
    fig_height: 6
---


```{r LOAD, echo=FALSE, cache=FALSE}

    #### load("dfRaceWorkplaceAndShares.rda") ### Only use data in tables, plots, and maps
    load("dfCensus2.rda") 
    load("dfTab1A1B2A2B3ABCDEF.rda")
    load("dfTab4.rda")   
    load("dfMap4.rda")
    load("dfPlot5Tab5beta1000.rda")
    load("dfTab67A7B7C7D7E7F8A8B8C8D8E8F.rda")
    load("APPENDIX.rda")  
    
    ###install.packages("gridExtra")
    library(prettydoc)
    library(maps)    
    library(mapproj) ### needed by ggplot2, but not installed automaticallly
    library(ggplot2)
    library(gridExtra)
    ### library(printr)
    library(grid)
    library(gtable)
    library(grid)

    ### Intending to use Yihui Xie's printr package for better tables later
    ### install.packages("devtools")
    ### library(devtools)
    ### install_github("yihui/printr")
    ### library(printr)
    ### detach('package:printr', unload = TRUE)
    
tt3 <- ttheme_minimal(
  core=list(bg_params = list(fill = blues9[1:7], col=NA),
            fg_params=list(fontface=3)),
  colhead=list(fg_params=list(col="navyblue", fontface=4L)),
  rowhead=list(fg_params=list(col="orange", fontface=3L)))


```

<P style="page-break-before: always">  
## Overview   

Kurosawa's [<b>Rashomon</b>](http://www.imdb.com/title/tt0042876/) challenged its viewers to puzzle over what they had seen. Four versions of a tragic event were presented, but each version had enough omissions and inconsistencies to alert the viewer that no version was the truth, the whole truth, and nothing but the truth. Even the supposedly neutral observer framed his version in a way to make himself look better. Some viewers concluded that the film's main point was that truth is unknowable. I'm not so pessimistic. To me the film is a reminder that truth is attainable but is rarely as simple as it first appears to be, and that multiple perspectives provide useful insights, even when they seem to be in conflict with each other.   

The four viewpoints presented in the following sections of this policy analysis are the perspectives that I encountered in my efforts to assemble data that would provide a broad context for productive discussions of diversity in the U.S. information technology sector.   

* [<b>Best States for American Black, Hispanic, Asian, and Female Tech – Vers 1.0f</b>](https://hbcu-levers.blogspot.com/2016/11/best-states-for-american-black-hispanic.html) 
* [<b>Foreign Professionals: U.S. Tech’s Other Pipelines – Version 1.0</b>](https://hbcu-levers.blogspot.com/2016/12/foreign-professionals-us-techs-other.html)   

Each view implies solution strategies, but different views imply different strategies. 

<small><i><center><a href="https://archimedes2kxx.github.io/BestStatesForBlackTech/Policies-4.html" target="_self">back-to-top</a></center></i></small>   
<P style="page-break-before: always">   
## Version 1 -- Racism and Sexism   

<b>Problem: low percentage women, Blacks, and Hispanics</b>   
The nation's attention was focused on this problem in 2014 by the responses of Google, Facebook, and other major Silicon Valley tech firms to requests from the Reverend Jesse Jackson, Jr., for the employment data in their annual EEOC reports. As was anticipated, the data showed that the percentage of women, Blacks, and Hispanics employed by these firms was well below the percentage of these groups in the nation's overall population.   

DATA DATA DATA My report on top four in Silicon Valley ... plus my data on Best States including maps and charts

<b>Cause: Racial and gender bias</b>   
The low percentages of women, Blacks, and Hispanics employed by Silicon Valley's leading employers was interpreted as indications of racial and gender bias in hiring processes

<b>Solutions: diversity/inclusion officers and diverse board members</b>  
Advocates demanded that diversity/inclusion officers be added to the human relations departments of the Valley's firms. THese officers would be charged with hiring more women and minoritieis. Adding diverse members to the boards of these firms would provide the required high level oversight to ensure that the diversity initiatives produced substantial results

<small><i><center><a href="https://archimedes2kxx.github.io/BestStatesForBlackTech/Policies-4.html" target="_self">back-to-top</a></center></i></small>  
<P style="page-break-before: always">   
## Version 2  -- Academic Pipelines   

<b>Problem: low percentage of women, Blacks, and Hispanics in tech</b>   
Some of the leadership of Silicon Valley viewed the same  EEOC data, but came to very different conclusions and different solutions than the Reverend Jackson and his associates

<b>Cause: low enrollments of women, Blacks, and Hispanics in academic pipelines</b> 
The Valley's leadership claimed that the low employment levels reflected  low enrollment levels of women, Blacks, and Hispanics in computer science and related college degree programs that led to careers in information technology. They also observed that the low enrollment levels in college programs reflected low enrollments in high school and middle school courses that stimulated young people's interests in computer science and related fields

<b>Solutions: Specialized college recruitment and support for K-12 programs </b>
Goggle and others tried to fill the academic pipelines by intensifying their recruitment of Black students from Historically Black Colleges and Universities (HBCUs). And many companies offered support for Black Girls Code, Code.org, and other organizations that ran programs that stimulate interest in computer sceience among K-12 students. 

DATA DATA DATA DATA ... my data about Black, Hispanic enrollments in top schools, espe in California 

Flaw -- lots of Black and Hispanic techs, SV has small demand, why no recruitment efforts??? Why no concern about competitive disadvantages of low diversity?? 


<small><i><center><a href="https://archimedes2kxx.github.io/BestStatesForBlackTech/Policies-4.html" target="_self">back-to-top</a></center></i></small>
<P style="page-break-before: always">  

## ... Comments -- Versions 1 and 2

* Little progress in Silicon Valley and the "explanation" of apologists "These things take time" is both ironic and unacceptable give the Valley's incessant self-praise about its capacity to "disrupt" and "fail fast"  

* My initial focus was on Black Techs, but my examination of data that showed substantial enrollments of Hispanic students in California's top schools removed all doubt that lack of employment in Silicon Valley was a reflection of of low supply levels in the Valley's pipelines

* Lack of progress suggest that neither perspective gets to the heart of the issue. Failure sometimes indicates that other actions of the actor are acting at cross purposes to the actor's stated goals   

* By the time I finished "Best States" I had acquired enough data about U,S, tech's extensive hiring of foreign techs to suspect that the increasing employment of these high tech migrant laborers might be the "cross purposes" initiative resopnsible for the lack of progress   

* As an aging Black techie who received his undergrad degree in engineering way back in 1962 from New York University, I find racial bias, conscious or unconscious, as implausible explanations of the Valley's lack of progress in increasing the percentage of Black technical staff on the Valley's payrolls. Why? Because there are too many Jewish Americans in the top management of the Valley's biggest and most successful companies. 



<small><i><center><a href="https://archimedes2kxx.github.io/BestStatesForBlackTech/Policies-4.html" target="_self">back-to-top</a></center></i></small>  
<P style="page-break-before: always">   
## Version 3 -- Competitive Advantage  


Problem: Not enough U.S. techs with satisfactory tech skills   
Cause: Curriculum of U.S. colleges and universities not evolving fast enough to keep pace with evolving technologies required by U.S. tech   
Solution: import increasing numbers of foreign professionals to fill this skills gap, especially from Asia where training seems to be keeping pace with technology and cost of living is lower than in Europe, expand H-1B visa, ... broad scale immigration reform to give U.S. tech access to unlimited foreign labor   
Flaw -- Why is there no limit to foreign recruitment?   

DATA... DATA ... DATA ... my data about foreign, including maps and charts

<small><i><center><a href="https://archimedes2kxx.github.io/BestStatesForBlackTech/Policies-4.html" target="_self">back-to-top</a></center></i></small>  
<P style="page-break-before: always">   
## Version 4 -- Maximum Profits   

DATA ... refer to same data about foreign

Problem: U.S. Tech, especially software development, is still labor intensive   
In order to sustain record profits in order to attract future investments, labor costs must be reduced   
Classic solution -- use cheaper labor, i.e., techs from other countries with much lower standards of living, e.g, therefore mostly from Asian countriess   
Flaw -- Japan that can say no ... defense industrial base ... cost benefit for entire economy ... permanent low share for Black techs can't compete with cheap labor   

<small><i><center><a href="https://archimedes2kxx.github.io/BestStatesForBlackTech/Policies-4.html" target="_self">back-to-top</a></center></i></small>
<P style="page-break-before: always">   
## ... Comments -- Versions 3 and 4 


<small><i><center><a href="https://archimedes2kxx.github.io/BestStatesForBlackTech/Policies-4.html" target="_self">back-to-top</a></center></i></small>
<P style="page-break-before: always">   
## ... Final Comments

<small><i><center><a href="https://archimedes2kxx.github.io/BestStatesForBlackTech/Policies-4.html" target="_self">back-to-top</a></center></i></small>


