---
title: "Best States Project Notes"
author: "Roy L Beasley"
date: "September 24, 2016"
output: html_document
---
This file contains notes that document problems encountered with the data, statistics, maps, tables, and plots -- and the solutions that I adopted.   

### A. Codebook files

* 



### B. Maps   

* Each of the four maps represented the percentage distributions of one racial/ethnic group. But I wanted the same color to represent 10% on each map, the same color to represent 20%, etc. That way readers could see how much more concentrated Asian techs were in California than Black techs were in Texas. I could not find a standard way to do this when I googled various descriptors. So I "cheated"   

* The District of Columbia is so small relative to the other states that it is invisible on the maps. I took advantage of this defect by codng my mapping function to give DC the same value on each map ==> 30% attained by Asian techs in California, which was the highest concentration atained by any of the four racial/ethnic groups in any state. DC should have had the same color as California, but since the area is so small, the color didn't even show up as a bright red dot ... :-)

### C. Using Git-io   

* I originally intended to copy and paste the HTML file for the report that was generated by R-Markdown on a page on my TECH-Levers blog. But when I directed my Chrome browser to "View Source", it displayed HTML plus some extensive encrypted coding. Nevertheless, I pasted it into the HTML view of a blank page. The text, maps, and plots appeared correctly. But most of the Cayman theme that I selected was lost,  specifically, the backgrounds on each of the tables, different font sizes and colors for different heading levels. Worst of all the  links to the full versions of Tables 4A, 4B, 4C, and 4D that opened these tables in in the same window as the report page were broken.   
 
* But when I hosted the page on GitHub's git-io server and accessed them via an iFrame on the page on my blogger, the all of theme elements were visible and the full tables appeared within the iFrame when their links were clicked.

* Using Git-io required that I copy all of the HTML pages for the report into a "doc" sub-folder of the project folder on Git-Hub. This meant that I had to make two commits and pushes. The first committed and pushed all my project files to Git-Hub, i.e, R-Markdown (.rmd), .cvs data files, etc. Then I had to copy the HTML files to the "doc" subfolder on my local Git repo, and commit and push them to the corresponding "doc" subfolder of my project on GitHub.







